# Generated by Django 4.2.3 on 2023-07-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('year', models.SmallIntegerField(null=True)),
                ('price', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
