# Generated by Django 4.2.3 on 2023-07-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_unique_title_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'My book', 'verbose_name_plural': 'My books'},
        ),
    ]
